version: '3'

services:
  web:
    container_name: somethingVue2
    build: ./docker/web
    ports:
      - 8080:8080
    volumes:
      - ./server:/app:cached
    tty: true
    stdin_open: true
    privileged: true
    command: /bin/sh